### ISSUE TITLE
Bad Image error on load

### ISSUE THREAD

**Issue by Stankye** [mrfearless/APISearch-Plugin-x64#2]
http://i.imgur.com/ZBvOoM4.png 

Any ideas? Windows 10 x64

**Comment by mrfearless** [comment]
After some google searching the closest i came across that explains this and has a potential link to solve it is this one: http://answers.ea.com/t5/Origin/Origin-exe-Bad-Image/td-p/4999278/page/4

> Good, now go here and download the "Visual Studio 2013 (VC++ 12.0)"  runtimes. (All three packages and both versions (x86 and x64) of the "Microsoft Visual C++ Redistributable Packages for Visual Studio 2013" 

The "here" is referring to this url: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I suspect any .dll (or .dp64) that is loaded up by x64dbg (or other programs) that make use of visual c runtimes could have a similar issue. So i dont think its a plugin issue, more a visual c runtime install/reinstallation issue thats causing the error.

Let me know how you get on with that, hopefully that fixes things. Fingers crossed.

**Comment by mrfearless** [comment]
Hopefully this has been resolved now.

**Comment by Stankye** [comment]
Sorry for the late reply. 

Reinstalled windows -> all good
Installed VS2015 -> error.

Fix: Dont install VS2015

**Comment by mrfearless** [comment]
Ok, thanks for the update.
